name: wallet
description: Edgeware Simple Wallet.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^3.1.1
  flutter_secure_storage: ^3.3.5
  flutter_svg: ^0.19.0
  qr_flutter: ^3.2.0
  google_fonts: ^1.1.0
  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  get: ^3.16.1
  get_storage: ^1.3.2
  path_provider: ^1.6.18
  connectivity: ">=0.4.9+3 <2.0.0"
  url_launcher: ^5.7.10
  camerawesome: ^0.1.1+1
  logger: ^0.9.4
  edgeware:
    path: ./packages/edgeware

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/

flutter_icons:
  android: true
  ios: true
  image_path: assets/png/icon.png

flutter_native_splash:
  image: assets/png/logo.png
  color: "#FFFFFFFF"
  android_disable_fullscreen: true
