export 'generate_account/controller.dart';
export 'generate_account/view.dart';
export 'home/controller.dart';
export 'home/view.dart';
export 'intro/view.dart';
export 'recover_account/controller.dart';
export 'recover_account/view.dart';
export 'splash/controller.dart';
export 'splash/view.dart';
