name: edgeware
description: FFI Binding for Edgeware.
version: 0.0.1
author: Shady Khalifa <shekohex@gmail.com>
homepage: 'https://github.com/shekohex/edgeware-wallet'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi:
  isolate:
  meta:

dev_dependencies:
  ffigen: ^1.1.0

flutter:
  plugin:
    platforms:
      android:
        package: re.edgewa.edgeware
        pluginClass: EdgewarePlugin
      ios:
        pluginClass: EdgewarePlugin

ffigen:
  output: "lib/ffi.dart"
  name: "RawEdgeware"
  description: "Edgeware Client Binding"
  array-workaround: false
  sort: true
  comments:
    style: any
    length: full
  headers:
    entry-points:
      - "../../native/edgeware/binding.h"
    include-directives:
      - "**binding.h"
