on: [push, pull_request]

name: Lints

jobs:
  combo:
    name: Clippy + rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true # TODO(shekohex): remove this once you can compile on nightly.
        with:
          command: fmt
          args: --all -- --check

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-lint-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true # TODO(shekohex): remove this once you can compile on nightly.
        with:
          command: clippy
          args: -- -D warnings
